FROM ubuntu:20.04 



RUN apt-get update && \
    apt-get install -y \
    wget \
    openjdk-11-jdk \
    git \
    && rm -rf /var/lib/apt/lists/*

# Download and install Jenkins
RUN wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add - && \
    sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list' && \
    apt-get update && \
    apt-get install -y jenkins


# Expose the default Jenkins port
EXPOSE 8080

# Start Jenkins
CMD ["java", "-jar", "/usr/share/jenkins/jenkins.war"]
