# Use the official PostgreSQL image as the base image
FROM postgres:13

# Set environment variables for PostgreSQL
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD puru21shiv
ENV POSTGRES_DB docker

# Expose the PostgreSQL port (default is 5432)
EXPOSE 5432
